start https://ninjaoutreach.com/startup-directories/
start http://www.beingpractical.com/2013/10/12/100-startup-directories-to-submit-your-startup-for-free/
start http://promotehour.com/
start https://inc42.com/startup-submission
start http://knowstartup.com/submit-startup/
start https://www.indianweb2.com/submit-profile/
start https://www.startupbutton.com/submit/
start http://www.thestartupjournal.com/submit/
start https://taalk.com/submit-startup/
start http://submitstartup.com/
start http://www.indianentrepreneur.com/submit-your-startup/
start http://www.mindcron.com/submit-new-startup/
start http://theventures.in/startup-submission/index.htm
start http://startoholics.in/submit-your-startup/
start https://betalist.com/submissions/new
start http://starup.in/
start http://www.indianstartups.com/p/AddStartup1
